name: Deploy Language content to Pages

on:
  workflow_call:
    inputs:
      generate_sitemap:
        description: 'Whether to generate sitemap.xml'
        required: false
        type: boolean
        default: true
      config_path:
        description: 'Path to config JSON file'
        required: false
        type: string
        default: 'lang.json'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repo
        uses: actions/checkout@v4

      - name: Checkout actions repo
        uses: actions/checkout@v4
        with:
          repository: ${{ job.workflow_repository }}
          ref: ${{ job.workflow_sha }}
          path: .github/actions-shared

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build and Generate Content
        env:
          BASE_URL: ${{ steps.pages.outputs.base_url }}
          GENERATE_SITEMAP: ${{ inputs.generate_sitemap }}
        run: |
          node .github/actions-shared/lang/lang_v2.js "${{ inputs.config_path }}"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
